# Generated by Django 4.2.2 on 2023-06-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brit_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('p_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('premium', models.TextField(blank=True, null=True)),
                ('next_premium', models.TextField(blank=True, null=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('dob', models.TextField(blank=True, null=True)),
                ('postal_address', models.TextField(blank=True, null=True)),
                ('telephone_number', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('pin', models.TextField(blank=True, null=True)),
                ('life_assured', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, null=True)),
                ('resident_country', models.CharField(blank=True, null=True)),
                ('sum_assured', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('Policy_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brit_users.policytypes')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('policy_status', models.CharField(blank=True, max_length=50, null=True)),
                ('policy_details', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('policy_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brit_users.policytypes')),
            ],
        ),
    ]
