# Generated by Django 4.2.2 on 2023-06-16 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brit_users', '0002_policytypes_userpolicy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='Policy_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='policy_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brit_users.policy'),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
