# Generated by Django 4.2.2 on 2023-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brit_users', '0003_userpolicy_is_draft_alter_userpolicy_policy_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpolicy',
            name='Policy_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='dob',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='frequency',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='life_assured',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='next_premium',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='pin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='postal_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='premium',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
