# Generated by Django 4.2.2 on 2023-06-21 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brit_users', '0004_alter_userpolicy_policy_number_alter_userpolicy_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
