# Generated by Django 4.2.2 on 2023-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brit_users', '0005_users_code_users_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='referral_link',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
