# Generated by Django 4.2.2 on 2023-06-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brit_users', '0007_policy_policy_image_alter_policy_policy_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
