# Generated by Django 4.2.2 on 2023-06-27 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brit_users', '0008_users_bio_users_profile_photo_users_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(max_length=350)),
                ('amount', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('transaction_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brit_users.users')),
            ],
        ),
    ]
