# Generated by Django 4.2.2 on 2023-06-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brit_users', '0010_alter_transaction_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='result_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
