# Generated by Django 4.2.2 on 2023-06-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brit_users', '0012_educationcontent_loyaltypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='claim_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='claim_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='claim_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
