# Generated by Django 4.2.2 on 2023-06-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brit_users', '0013_userpolicy_claim_amount_userpolicy_claim_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='available_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='redeemed_points',
            field=models.IntegerField(default=0),
        ),
    ]
